apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc-volume
  labels:
    type: local1
spec:
  storageClassName: "manual"
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: data-pv-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-pvc-volume
  labels:
    type: local1
spec:
  storageClassName: "manual"
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: auth-pv-volume
---
